pipeline {
    agent { // using a global agent
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment { // define environment variable
        CI = true
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh' // do the deploy
                input message: 'Are you finished using the web site? (Click "Exit" to kill the app)' // create a message on Jenkins to interact
                sh './jenkins/scripts/kill.sh' // kill the app
            }
        }
    }
}
